export const DEFAULT_CONFIG = {
  betspotCount: 5,
  glowRadius: 5,
  ellipse: { b: 20, a: 76 },
  headRadius: 5,
  tailRadius: 1,
  sparkColor: "#f1eb9d",
  glowColor: "#fdcb3d",
  paths: [
    {
      id: 1,
      type: "spark",
      startVertex: "BR",
      animationTimeMs: 750,
      endVertex: "TL",
      delay: 0,
      ellipseTiltDeg: -45,
      ellipseRotationDeg: -2,
      sparkColor: "#f1eb9d",
      enabled: true,
    },
    {
      id: 2,
      type: "spark",
      startVertex: "BL",
      endVertex: "TR",
      delay: 170,
      animationTimeMs: 710,
      ellipseTiltDeg: 45,
      ellipseRotationDeg: 2,
      sparkColor: "#f1eb9d",
      enabled: true,
    },
    {
      id: 7,
      type: "spark",
      startVertex: "L",
      endVertex: "R",
      delay: 380,
      animationTimeMs: 1040,
      sparkColor: "#f1eb9d",
      enabled: true,
    },
    {
      id: 8,
      type: "svg",
      delay: 540,
      animationTimeMs: 1000,
      enabled: true,
      maxScale: 1.1,
      glowSpread: 0.12,
    },
    {
      id: 9,
      type: "spin",
      delay: 380,
      animationTimeMs: 14500,
      enabled: true,
      borderRadius: 6.75,
      headColor: "#ffeecc",
      tailColor: "#f8b778",
    },
    {
      id: 10,
      type: "multiplier",
      delay: 780,
      animationTimeMs: 1930,
      enabled: true,
      phase1Duration: 210,
      phase2Duration: 450,
      phase3Duration: 850,
      phase4Duration: 500,
      maxScale: 1.2,
      text: "50x",
    },
    {
      id: 11,
      type: "multiplier",
      delay: 3510,
      animationTimeMs: 3830,
      enabled: true,
      phase1Duration: 500,
      phase2Duration: 630,
      phase3Duration: 2200,
      phase4Duration: 500,
      maxScale: 1,
      text: "50x",
    },
    {
      id: 12,
      type: "multiplier",
      delay: 7850,
      animationTimeMs: 4120,
      enabled: true,
      phase1Duration: 500,
      phase2Duration: 370,
      phase3Duration: 2750,
      phase4Duration: 500,
      maxScale: 1,
      text: "50x",
    },
    {
      id: 13,
      type: "multiplier",
      delay: 12560,
      animationTimeMs: 2300,
      enabled: true,
      phase1Duration: 500,
      phase2Duration: 150,
      phase3Duration: 1200,
      phase4Duration: 500,
      maxScale: 1,
      text: "50x",
    },
  ],
};
