export const DEFAULT_CONFIG = {
  betspotCount: 1,
  ellipse: { b: 8.5, a: 37 },
  paths: [
    {
      id: 1,
      type: "circle-spark",
      startVertex: "BR",
      // animationTimeMs: 750,
      animationTimeMs: 375,
      endVertex: "TL",
      delay: 0,
      ellipseTiltDeg: -45,
      ellipseRotationDeg: -2,
      sparkColor: "#f1eb9d",
      headRadius: 2,
      tailRadius: 0.4,
      length: 20,
      dotCount: 100,
      enabled: true,
      // Layer configuration for 3-layer spark structure
      whiteCenterRatio: 0.1,
      glowRadiusMultiplier: 0.5,
      glowOpacityStart: 1.2,
      glowSideSuppression: 0.75,
      // Head tapering (tip)
      headTaperRatio: 0.08,
      tipRadius: 0.5,
      glowRadius: 0.5,
      glowOpacity: 0.15,
      headCurve: 0.2,
      whiteCoverage: 0.92,
    },
    {
      id: 2,
      type: "circle-spark",
      startVertex: "BL",
      endVertex: "TR",
      delay: 170,
      // animationTimeMs: 710,
      animationTimeMs: 355,
      ellipseTiltDeg: 45,
      ellipseRotationDeg: 2,
      sparkColor: "#f1eb9d",
      headRadius: 2,
      tailRadius: 0.4,
      length: 20, // Length of the spark in pixels
      dotCount: 100,
      enabled: true,
      whiteCenterRatio: 0.1,
      glowRadiusMultiplier: 0.5,
      glowOpacityStart: 1.2,
      glowSideSuppression: 0.75,
      headTaperRatio: 0.08,
      tipRadius: 0.5,
      glowRadius: 0.5,
      glowOpacity: 0.15,
      headCurve: 0.2,
      whiteCoverage: 0.92,
    },
    {
      id: 7,
      type: "circle-spark",
      startVertex: "L",
      endVertex: "R",
      delay: 380,
      // animationTimeMs: 1040,
      animationTimeMs: 520,
      sparkColor: "#f1eb9d",
      headRadius: 2,
      tailRadius: 0.4,
      length: 20, // Length of the spark in pixels
      dotCount: 100,
      enabled: true,
      whiteCenterRatio: 0.1,
      glowRadiusMultiplier: 0.5,
      glowOpacityStart: 1.2,
      glowSideSuppression: 0.75,
      headTaperRatio: 0.08,
      tipRadius: 0.5,
      glowRadius: 0.5,
      glowOpacity: 0.15,
      headCurve: 0.2,
      whiteCoverage: 0.92,
    },
    {
      id: 9,
      type: "factorial-noise",
      delay: 430,
      animationTimeMs: 420,
      enabled: true,
    },
    {
      id: 8,
      type: "svg",
      delay: 540,
      animationTimeMs: 1000,
      enabled: true,
      maxScale: 1.1,
      glowSpread: 0.12,
    },
    {
      id: 11,
      type: "black-hole",
      delay: 660,
      phase1TimeMs: 280,
      phase2TimeMs: 50,
      enabled: true,
    },
    {
      id: 10,
      type: "spark-spin",
      delay: 380,
      animationTimeMs: 14500,
      enabled: true,
      borderRadius: 6.75,
      sparkColor: "#ffaa25",
      headRadius: 2,
      tailRadius: 0.4,
      dotCount: 100,
      whiteCenterRatio: 0.8,
      glowRadius: 0.2,
      glowOpacity: 1,
      headTaperRatio: 0.08,
      headCurve: 0.2,
      whiteCoverage: 0.95,
    },
    {
      id: 14,
      type: "multiplier",
      delay: 780,
      animationTimeMs: 1930,
      enabled: true,
      phase1Duration: 210,
      phase2Duration: 450,
      phase3Duration: 850,
      phase4Duration: 500,
      maxScale: 1.2,
      text: "50x",
    },
    {
      id: 15,
      type: "multiplier",
      delay: 3510,
      animationTimeMs: 3830,
      enabled: true,
      phase1Duration: 500,
      phase2Duration: 630,
      phase3Duration: 2200,
      phase4Duration: 500,
      maxScale: 1,
      text: "50x",
    },
    {
      id: 16,
      type: "multiplier",
      delay: 7850,
      animationTimeMs: 4120,
      enabled: true,
      phase1Duration: 500,
      phase2Duration: 370,
      phase3Duration: 2750,
      phase4Duration: 500,
      maxScale: 1,
      text: "50x",
    },
    {
      id: 17,
      type: "multiplier",
      delay: 12560,
      animationTimeMs: 2300,
      enabled: true,
      phase1Duration: 500,
      phase2Duration: 150,
      phase3Duration: 1200,
      phase4Duration: 500,
      maxScale: 1,
      text: "50x",
    },
  ],
};
